version: '3'
services:
  api:
    image: 'jochri3/taskify_hobby_api'
    mem_limit: 128m
    hostname: api
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      PGDATABASE: ${PGDATABASE}
      PGHOST: ${PGHOST}
      PGPASSWORD: ${PGPASSWORD}
      PGPORT: ${PGPORT}
      PGUSER: ${PGUSER}
      JWT_SECRET: ${JWT_SECRET}
      JWT_TOKEN_AUDIENCE: ${JWT_TOKEN_AUDIENCE}
      JWT_TOKEN_ISSUER: ${JWT_TOKEN_ISSUER}
      JWT_ACCESS_TOKEN_TTL: ${JWT_ACCESS_TOKEN_TTL}
      JWT_REFRESH_TOKEN_TTL: ${JWT_REFRESH_TOKEN_TTL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

  nginx:
    image: 'jochri3/taskify_hobby_nginx'
    mem_limit: 128m
    hostname: nginx
    ports:
      - '80:80'
