version: "3"

services:
#  nginx:
#    depends_on:
#      - api
##      - client
#    restart: always
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./nginx
#    ports:
#      - "80:80"
#  api:
#    container_name: taskify_api
#    env_file:
#      - './api/.env.docker'
#    build:
#      dockerfile: Dockerfile.dev
#      context: ./api
#    volumes:
#      - /app/node_modules
#      - ./api:/app
#    environment:
#      DATABASE_URL: ${DATABASE_URL}
#    depends_on:
#      - db
#    expose:
#      - "3000:3000"

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5555:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
