name: ci
on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nodejs 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - run: docker build -t jochri3/taskify_hobby_api -f ./api/Dockerfile ./api
      # - run: docker run -e CI=true jochri3/taskify_hobby_api pnpm test -- --coverage

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push API
        uses: docker/build-push-action@v4
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taskify_hobby_api

      - name: Build and push Nginx
        uses: docker/build-push-action@v4
        with:
          context: ./nginx
          file: ./nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/taskify_hobby_nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: taskify
          environment_name: Taskify-env
          existing_bucket_name: elasticbeanstalk-us-east-1-960061664240
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
